-- Deterministic reference/lookup data. The 10,000-employee dataset itself is
-- generated by the application seeder (see SeedRunner), not shipped as SQL,
-- so it can be regenerated/varied without a new migration.
--
-- FX rates are a fixed snapshot for cross-country payroll reporting, not a
-- live feed -- see docs/requirements.md for why.

INSERT INTO currency (code, fx_to_usd) VALUES
    ('USD', 1.000000),
    ('GBP', 1.270000),
    ('EUR', 1.080000),
    ('INR', 0.012000),
    ('SGD', 0.740000),
    ('AUD', 0.660000),
    ('BRL', 0.170000);

INSERT INTO country (code, name, currency_code) VALUES
    ('US', 'United States', 'USD'),
    ('GB', 'United Kingdom', 'GBP'),
    ('DE', 'Germany', 'EUR'),
    ('FR', 'France', 'EUR'),
    ('IN', 'India', 'INR'),
    ('SG', 'Singapore', 'SGD'),
    ('AU', 'Australia', 'AUD'),
    ('BR', 'Brazil', 'BRL');

INSERT INTO department (name) VALUES
    ('Engineering'),
    ('Sales'),
    ('Marketing'),
    ('Finance'),
    ('Human Resources'),
    ('Operations'),
    ('Customer Support'),
    ('Product'),
    ('Legal'),
    ('Design');
